-- MySQL Script generated by MySQL Workbench
-- Mo 14 Sep 2020 19:24:31 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drops
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema drops
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `drops` ;
USE `drops` ;

-- -----------------------------------------------------
-- Table `drops`.`drops_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`drops_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `confirmed` TINYINT NOT NULL,
  `privacy_policy` TINYINT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`password_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`password_info` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `hasher` VARCHAR(45) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `drops_user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_password_info_drops_user1_idx` (`drops_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_password_info_drops_user1`
    FOREIGN KEY (`drops_user_id`)
    REFERENCES `drops`.`drops_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`model` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `service` VARCHAR(45) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`access` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `service` VARCHAR(45) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `drops_user_id` BIGINT(20) NOT NULL,
  `model_id` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_access_user_drops_user1_idx` (`drops_user_id` ASC) VISIBLE,
  UNIQUE INDEX `index3` (`drops_user_id` ASC, `model_id` ASC, `service` ASC) VISIBLE,
  INDEX `fk_access_model1_idx` (`model_id` ASC) VISIBLE,
  CONSTRAINT `fk_access_user_drops_user1`
    FOREIGN KEY (`drops_user_id`)
    REFERENCES `drops`.`drops_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_access_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `drops`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`access_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`access_token` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(45) NOT NULL,
  `t_case` VARCHAR(45) NOT NULL,
  `redirect_url` VARCHAR(255) NOT NULL,
  `expired` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `drops_user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_access_token_drops_user1_idx` (`drops_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_access_token_drops_user1`
    FOREIGN KEY (`drops_user_id`)
    REFERENCES `drops`.`drops_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`profile` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(64) NULL,
  `gender` ENUM('divers', 'male', 'female', 'none') NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `drops_user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_profile_drops_user1_idx` (`drops_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_drops_user1`
    FOREIGN KEY (`drops_user_id`)
    REFERENCES `drops`.`drops_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`avatar` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `profile_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avatar_profile1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_avatar_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `drops`.`profile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `drops`.`access_right`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drops`.`access_right` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `right` VARCHAR(45) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  `access_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index3` (`right` ASC, `access_id` ASC) VISIBLE,
  INDEX `fk_access_right_access1_idx` (`access_id` ASC) VISIBLE,
  CONSTRAINT `fk_access_right_access1`
    FOREIGN KEY (`access_id`)
    REFERENCES `drops`.`access` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
