-- MySQL Script generated by MySQL Workbench
-- Do 16 Jul 2020 15:52:19 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mail
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mail` ;
USE `mail` ;

-- -----------------------------------------------------
-- Table `mail`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail`.`template` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `salutation` VARCHAR(45) NOT NULL,
  `head_text` LONGTEXT NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `footer_text` LONGTEXT NOT NULL,
  `updated` BIGINT(20) NULL,
  `created` BIGINT(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
